#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 11 19:35:41 2020

@author: swapnil
"""

import socket as sk
s=sk.socket() #default TCP socket is formed
host=sk.gethostname()
port=8085
s.bind((host,port))
print("Waiting for Connection......")
print("Host name : ",host)
s.listen(1)

while True:
    conn,addr=s.accept()
    print("Connected To : ",addr)
    msg=input("Enter Message : ")
    conn.send(msg.encode())
    print("Waiting for New Connection......")
    #conn.close()
    
s.close()
